package model

type CodeEntry struct {
	Code   string
	Label  string
	Class  string
	Weight int
}

var FirelineCodes = []CodeEntry{
	{Code: "OBS-001", Label: "thermal rise", Class: "observation", Weight: 1},
	{Code: "OBS-002", Label: "smoke plume", Class: "observation", Weight: 2},
	{Code: "OBS-003", Label: "image hotspot", Class: "observation", Weight: 3},
	{Code: "OBS-004", Label: "wind shift", Class: "observation", Weight: 2},
	{Code: "OBS-005", Label: "ash fall", Class: "observation", Weight: 2},
	{Code: "OBS-006", Label: "dry lightning", Class: "observation", Weight: 3},
	{Code: "OBS-007", Label: "ember travel", Class: "observation", Weight: 3},
	{Code: "OBS-008", Label: "canopy glow", Class: "observation", Weight: 3},
	{Code: "OBS-009", Label: "night contrast", Class: "observation", Weight: 1},
	{Code: "OBS-010", Label: "manual sighting", Class: "observation", Weight: 2},
	{Code: "INC-001", Label: "candidate", Class: "incident", Weight: 1},
	{Code: "INC-002", Label: "confirmed", Class: "incident", Weight: 2},
	{Code: "INC-003", Label: "attacking", Class: "incident", Weight: 3},
	{Code: "INC-004", Label: "contained", Class: "incident", Weight: 4},
	{Code: "INC-005", Label: "closed", Class: "incident", Weight: 5},
	{Code: "INC-006", Label: "reopened", Class: "incident", Weight: 3},
	{Code: "INC-007", Label: "merged", Class: "incident", Weight: 3},
	{Code: "INC-008", Label: "alias", Class: "incident", Weight: 2},
	{Code: "INC-009", Label: "stale", Class: "incident", Weight: 1},
	{Code: "INC-010", Label: "recovered", Class: "incident", Weight: 2},
	{Code: "RES-001", Label: "water point", Class: "resource", Weight: 2},
	{Code: "RES-002", Label: "water corridor", Class: "resource", Weight: 3},
	{Code: "RES-003", Label: "fencing token", Class: "resource", Weight: 4},
	{Code: "RES-004", Label: "lease", Class: "resource", Weight: 3},
	{Code: "RES-005", Label: "release", Class: "resource", Weight: 2},
	{Code: "RES-006", Label: "refill", Class: "resource", Weight: 1},
	{Code: "RES-007", Label: "reserve", Class: "resource", Weight: 3},
	{Code: "RES-008", Label: "occupied", Class: "resource", Weight: 4},
	{Code: "RES-009", Label: "available", Class: "resource", Weight: 1},
	{Code: "RES-010", Label: "compensation", Class: "resource", Weight: 4},
	{Code: "AIR-001", Label: "flight plan", Class: "aircraft", Weight: 2},
	{Code: "AIR-002", Label: "no fly zone", Class: "aircraft", Weight: 4},
	{Code: "AIR-003", Label: "perimeter revision", Class: "aircraft", Weight: 4},
	{Code: "AIR-004", Label: "drop mission", Class: "aircraft", Weight: 3},
	{Code: "AIR-005", Label: "route freeze", Class: "aircraft", Weight: 3},
	{Code: "AIR-006", Label: "fuel check", Class: "aircraft", Weight: 2},
	{Code: "AIR-007", Label: "water load", Class: "aircraft", Weight: 2},
	{Code: "AIR-008", Label: "pilot brief", Class: "aircraft", Weight: 1},
	{Code: "AIR-009", Label: "corridor entry", Class: "aircraft", Weight: 4},
	{Code: "AIR-010", Label: "airspace exit", Class: "aircraft", Weight: 2},
	{Code: "RAD-001", Label: "dispatch message", Class: "radio", Weight: 2},
	{Code: "RAD-002", Label: "arrival ack", Class: "radio", Weight: 3},
	{Code: "RAD-003", Label: "unable ack", Class: "radio", Weight: 3},
	{Code: "RAD-004", Label: "repeat request", Class: "radio", Weight: 2},
	{Code: "RAD-005", Label: "channel change", Class: "radio", Weight: 1},
	{Code: "RAD-006", Label: "message owner", Class: "radio", Weight: 4},
	{Code: "RAD-007", Label: "thread migration", Class: "radio", Weight: 4},
	{Code: "RAD-008", Label: "checksum", Class: "radio", Weight: 2},
	{Code: "RAD-009", Label: "packet expiry", Class: "radio", Weight: 2},
	{Code: "RAD-010", Label: "broker retry", Class: "radio", Weight: 3},
	{Code: "ALR-001", Label: "evacuation", Class: "alert", Weight: 4},
	{Code: "ALR-002", Label: "shelter", Class: "alert", Weight: 3},
	{Code: "ALR-003", Label: "withdrawal", Class: "alert", Weight: 4},
	{Code: "ALR-004", Label: "pending withdrawal", Class: "alert", Weight: 4},
	{Code: "ALR-005", Label: "broker unavailable", Class: "alert", Weight: 5},
	{Code: "ALR-006", Label: "public area", Class: "alert", Weight: 2},
	{Code: "ALR-007", Label: "warning level", Class: "alert", Weight: 3},
	{Code: "ALR-008", Label: "update", Class: "alert", Weight: 2},
	{Code: "ALR-009", Label: "retraction", Class: "alert", Weight: 3},
	{Code: "ALR-010", Label: "delivery receipt", Class: "alert", Weight: 2},
	{Code: "LOG-001", Label: "event append", Class: "journal", Weight: 1},
	{Code: "LOG-002", Label: "snapshot", Class: "journal", Weight: 2},
	{Code: "LOG-003", Label: "recovery", Class: "journal", Weight: 3},
	{Code: "LOG-004", Label: "alias map", Class: "journal", Weight: 4},
	{Code: "LOG-005", Label: "mission index", Class: "journal", Weight: 4},
	{Code: "LOG-006", Label: "checkpoint", Class: "journal", Weight: 3},
	{Code: "LOG-007", Label: "retention", Class: "journal", Weight: 2},
	{Code: "LOG-008", Label: "evidence", Class: "journal", Weight: 3},
	{Code: "LOG-009", Label: "operation result", Class: "journal", Weight: 3},
	{Code: "LOG-010", Label: "digest", Class: "journal", Weight: 2},
	{Code: "CREW-001", Label: "assembly", Class: "crew", Weight: 2},
	{Code: "CREW-002", Label: "medical", Class: "crew", Weight: 3},
	{Code: "CREW-003", Label: "equipment", Class: "crew", Weight: 3},
	{Code: "CREW-004", Label: "readiness", Class: "crew", Weight: 3},
	{Code: "CREW-005", Label: "rally point", Class: "crew", Weight: 2},
	{Code: "CREW-006", Label: "handoff", Class: "crew", Weight: 2},
	{Code: "CREW-007", Label: "progress", Class: "crew", Weight: 2},
	{Code: "CREW-008", Label: "relief", Class: "crew", Weight: 1},
	{Code: "CREW-009", Label: "sector lead", Class: "crew", Weight: 2},
	{Code: "CREW-010", Label: "field proof", Class: "crew", Weight: 4},
	{Code: "SEC-001", Label: "north ridge", Class: "sector", Weight: 2},
	{Code: "SEC-002", Label: "pine valley", Class: "sector", Weight: 2},
	{Code: "SEC-003", Label: "river pass", Class: "sector", Weight: 2},
	{Code: "SEC-004", Label: "adjacency", Class: "sector", Weight: 1},
	{Code: "SEC-005", Label: "route", Class: "sector", Weight: 2},
	{Code: "SEC-006", Label: "coverage", Class: "sector", Weight: 2},
	{Code: "SEC-007", Label: "elevation", Class: "sector", Weight: 1},
	{Code: "SEC-008", Label: "exposure", Class: "sector", Weight: 3},
	{Code: "SEC-009", Label: "vegetation", Class: "sector", Weight: 2},
	{Code: "SEC-010", Label: "risk", Class: "sector", Weight: 4},
}
