package app

type ProtocolStep struct {
	ID      string `json:"id"`
	Phase   string `json:"phase"`
	Actor   string `json:"actor"`
	Action  string `json:"action"`
	Outcome string `json:"outcome"`
}

var BuiltinProtocols = []ProtocolStep{
	{
		ID:      "FL-001",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "accept sensor envelope",
		Outcome: "accept sensor envelope is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-002",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "validate sensor identity",
		Outcome: "validate sensor identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-003",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "normalize sector identity",
		Outcome: "normalize sector identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-004",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "preserve event timestamp",
		Outcome: "preserve event timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-005",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "record receive timestamp",
		Outcome: "record receive timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-006",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "assign ingest sequence",
		Outcome: "assign ingest sequence is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-007",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "retain collection epoch",
		Outcome: "retain collection epoch is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-008",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "load matching calibration",
		Outcome: "load matching calibration is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-009",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "apply calibration offsets",
		Outcome: "apply calibration offsets is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-010",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "classify thermal signal",
		Outcome: "classify thermal signal is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-011",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "classify smoke signal",
		Outcome: "classify smoke signal is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-012",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "classify image hotspot",
		Outcome: "classify image hotspot is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-013",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "persist observation event",
		Outcome: "persist observation event is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-014",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "attach observation history",
		Outcome: "attach observation history is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-015",
		Phase:   "observation",
		Actor:   "observer",
		Action:  "return accepted identity",
		Outcome: "return accepted identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-016",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "build feature vector",
		Outcome: "build feature vector is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-017",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "score thermal evidence",
		Outcome: "score thermal evidence is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-018",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "score smoke evidence",
		Outcome: "score smoke evidence is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-019",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "score image evidence",
		Outcome: "score image evidence is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-020",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "combine confidence inputs",
		Outcome: "combine confidence inputs is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-021",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "group candidate by sector",
		Outcome: "group candidate by sector is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-022",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "retain incident generation",
		Outcome: "retain incident generation is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-023",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "rank sector candidates",
		Outcome: "rank sector candidates is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-024",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "reject low confidence input",
		Outcome: "reject low confidence input is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-025",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "archive stale candidate",
		Outcome: "archive stale candidate is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-026",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "promote current candidate",
		Outcome: "promote current candidate is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-027",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "record detection report",
		Outcome: "record detection report is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-028",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "publish candidate identity",
		Outcome: "publish candidate identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-029",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "retain source observation",
		Outcome: "retain source observation is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-030",
		Phase:   "detection",
		Actor:   "detector",
		Action:  "return detection outcome",
		Outcome: "return detection outcome is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-031",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "create candidate incident",
		Outcome: "create candidate incident is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-032",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "confirm field incident",
		Outcome: "confirm field incident is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-033",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "advance attacking stage",
		Outcome: "advance attacking stage is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-034",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "record contained evidence",
		Outcome: "record contained evidence is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-035",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "close terminal incident",
		Outcome: "close terminal incident is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-036",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "retain generation identity",
		Outcome: "retain generation identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-037",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "archive historical input",
		Outcome: "archive historical input is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-038",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "link mission identity",
		Outcome: "link mission identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-039",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "link observation identity",
		Outcome: "link observation identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-040",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "merge adjacent incident",
		Outcome: "merge adjacent incident is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-041",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "create child alias",
		Outcome: "create child alias is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-042",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "preserve primary owner",
		Outcome: "preserve primary owner is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-043",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "reject invalid transition",
		Outcome: "reject invalid transition is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-044",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "record transition event",
		Outcome: "record transition event is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-045",
		Phase:   "incident",
		Actor:   "incident lead",
		Action:  "return current incident",
		Outcome: "return current incident is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-046",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "publish boundary revision",
		Outcome: "publish boundary revision is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-047",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "copy approved boundary",
		Outcome: "copy approved boundary is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-048",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "copy restricted corridors",
		Outcome: "copy restricted corridors is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-049",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "record wind bearing",
		Outcome: "record wind bearing is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-050",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "advance revision number",
		Outcome: "advance revision number is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-051",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "retain approved timestamp",
		Outcome: "retain approved timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-052",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "calculate corridor risk",
		Outcome: "calculate corridor risk is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-053",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "validate flight revision",
		Outcome: "validate flight revision is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-054",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "freeze active route",
		Outcome: "freeze active route is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-055",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "preserve historical revision",
		Outcome: "preserve historical revision is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-056",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "reject stale new plan",
		Outcome: "reject stale new plan is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-057",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "build current waypoints",
		Outcome: "build current waypoints is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-058",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "record route decision",
		Outcome: "record route decision is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-059",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "list revision history",
		Outcome: "list revision history is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-060",
		Phase:   "perimeter",
		Actor:   "air coordinator",
		Action:  "return current revision",
		Outcome: "return current revision is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-061",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "validate operation identity",
		Outcome: "validate operation identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-062",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "validate incident identity",
		Outcome: "validate incident identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-063",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "validate assignee identity",
		Outcome: "validate assignee identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-064",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "validate rally point",
		Outcome: "validate rally point is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-065",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "recover prior operation",
		Outcome: "recover prior operation is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-066",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "derive stable mission identity",
		Outcome: "derive stable mission identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-067",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "reserve required corridor",
		Outcome: "reserve required corridor is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-068",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "bind perimeter revision",
		Outcome: "bind perimeter revision is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-069",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "create aircraft route",
		Outcome: "create aircraft route is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-070",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "attach mission to incident",
		Outcome: "attach mission to incident is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-071",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "publish radio message",
		Outcome: "publish radio message is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-072",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "persist operation result",
		Outcome: "persist operation result is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-073",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "return original retry result",
		Outcome: "return original retry result is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-074",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "list active missions",
		Outcome: "list active missions is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-075",
		Phase:   "dispatch",
		Actor:   "dispatcher",
		Action:  "record dispatch outcome",
		Outcome: "record dispatch outcome is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-076",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "load corridor capacity",
		Outcome: "load corridor capacity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-077",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "lock capacity transition",
		Outcome: "lock capacity transition is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-078",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "check current owners",
		Outcome: "check current owners is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-079",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "advance fencing token",
		Outcome: "advance fencing token is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-080",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "create owned lease",
		Outcome: "create owned lease is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-081",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "attach mission identity",
		Outcome: "attach mission identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-082",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "attach owner identity",
		Outcome: "attach owner identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-083",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "record acquired timestamp",
		Outcome: "record acquired timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-084",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "reject occupied corridor",
		Outcome: "reject occupied corridor is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-085",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "verify release owner",
		Outcome: "verify release owner is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-086",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "record released timestamp",
		Outcome: "record released timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-087",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "decrement owner count",
		Outcome: "decrement owner count is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-088",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "retain lease history",
		Outcome: "retain lease history is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-089",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "restore active lease",
		Outcome: "restore active lease is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-090",
		Phase:   "resource",
		Actor:   "resource coordinator",
		Action:  "return capacity state",
		Outcome: "return capacity state is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-091",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "build dispatch message",
		Outcome: "build dispatch message is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-092",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "attach mission identity",
		Outcome: "attach mission identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-093",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "attach incident identity",
		Outcome: "attach incident identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-094",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "record send timestamp",
		Outcome: "record send timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-095",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "encode packet header",
		Outcome: "encode packet header is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-096",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "calculate packet checksum",
		Outcome: "calculate packet checksum is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-097",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "queue broker delivery",
		Outcome: "queue broker delivery is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-098",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "record broker failure",
		Outcome: "record broker failure is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-099",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "schedule retry attempt",
		Outcome: "schedule retry attempt is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-100",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "accept field acknowledgement",
		Outcome: "accept field acknowledgement is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-101",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "record acknowledgement actor",
		Outcome: "record acknowledgement actor is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-102",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "record acknowledgement time",
		Outcome: "record acknowledgement time is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-103",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "migrate merged thread",
		Outcome: "migrate merged thread is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-104",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "list pending messages",
		Outcome: "list pending messages is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-105",
		Phase:   "radio",
		Actor:   "radio operator",
		Action:  "return message state",
		Outcome: "return message state is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-106",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "publish evacuation alert",
		Outcome: "publish evacuation alert is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-107",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "attach incident identity",
		Outcome: "attach incident identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-108",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "record public area",
		Outcome: "record public area is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-109",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "record alert message",
		Outcome: "record alert message is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-110",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "mark alert active",
		Outcome: "mark alert active is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-111",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "request alert withdrawal",
		Outcome: "request alert withdrawal is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-112",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "propagate channel failure",
		Outcome: "propagate channel failure is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-113",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "mark withdrawal pending",
		Outcome: "mark withdrawal pending is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-114",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "record withdrawal error",
		Outcome: "record withdrawal error is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-115",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "schedule withdrawal retry",
		Outcome: "schedule withdrawal retry is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-116",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "complete channel withdrawal",
		Outcome: "complete channel withdrawal is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-117",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "mark alert inactive",
		Outcome: "mark alert inactive is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-118",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "clear retry state",
		Outcome: "clear retry state is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-119",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "list public alert state",
		Outcome: "list public alert state is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-120",
		Phase:   "alert",
		Actor:   "public safety lead",
		Action:  "return withdrawal outcome",
		Outcome: "return withdrawal outcome is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-121",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "validate report identity",
		Outcome: "validate report identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-122",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "validate image identity",
		Outcome: "validate image identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-123",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "attach incident identity",
		Outcome: "attach incident identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-124",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "record field summary",
		Outcome: "record field summary is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-125",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "record submission timestamp",
		Outcome: "record submission timestamp is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-126",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "encode report metadata",
		Outcome: "encode report metadata is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-127",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "write report metadata",
		Outcome: "write report metadata is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-128",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "write evidence bytes",
		Outcome: "write evidence bytes is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-129",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "sync evidence files",
		Outcome: "sync evidence files is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-130",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "verify both files exist",
		Outcome: "verify both files exist is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-131",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "reject incomplete proof",
		Outcome: "reject incomplete proof is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-132",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "allow same report retry",
		Outcome: "allow same report retry is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-133",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "advance contained stage",
		Outcome: "advance contained stage is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-134",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "request alert withdrawal",
		Outcome: "request alert withdrawal is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-135",
		Phase:   "evidence",
		Actor:   "field supervisor",
		Action:  "return proof outcome",
		Outcome: "return proof outcome is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-136",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "open snapshot file",
		Outcome: "open snapshot file is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-137",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "decode snapshot payload",
		Outcome: "decode snapshot payload is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-138",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "validate snapshot identity",
		Outcome: "validate snapshot identity is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-139",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "load incident aliases",
		Outcome: "load incident aliases is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-140",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "resolve alias chains",
		Outcome: "resolve alias chains is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-141",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "load incident records",
		Outcome: "load incident records is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-142",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "normalize primary incidents",
		Outcome: "normalize primary incidents is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-143",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "load mission records",
		Outcome: "load mission records is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-144",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "normalize mission owners",
		Outcome: "normalize mission owners is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-145",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "load resource leases",
		Outcome: "load resource leases is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-146",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "rebuild public indexes",
		Outcome: "rebuild public indexes is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-147",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "replay later events",
		Outcome: "replay later events is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-148",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "advance replay cursor",
		Outcome: "advance replay cursor is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-149",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "verify checkpoint digest",
		Outcome: "verify checkpoint digest is durable and visible to the next FireLine component",
	},
	{
		ID:      "FL-150",
		Phase:   "recovery",
		Actor:   "recovery coordinator",
		Action:  "return recovered state",
		Outcome: "return recovered state is durable and visible to the next FireLine component",
	},
}

func ProtocolStepCount() int { return len(BuiltinProtocols) }
