package app

type Scenario struct {
	ID        string
	Trigger   string
	Expected  string
	Component string
}

var Scenarios = []Scenario{
	{ID: "late-frame-01", Trigger: "closed incident receives old thermal frame", Expected: "archive frame", Component: "sensor/incident"},
	{ID: "late-frame-02", Trigger: "closed incident receives old smoke frame", Expected: "archive frame", Component: "sensor/incident"},
	{ID: "late-frame-03", Trigger: "closed incident receives old image frame", Expected: "archive frame", Component: "sensor/incident"},
	{ID: "late-frame-04", Trigger: "current epoch receives thermal frame", Expected: "candidate", Component: "sensor/detector"},
	{ID: "late-frame-05", Trigger: "current epoch receives smoke frame", Expected: "candidate", Component: "sensor/detector"},
	{ID: "late-frame-06", Trigger: "delayed observation crosses a closure", Expected: "no reopen", Component: "sensor/incident"},
	{ID: "late-frame-07", Trigger: "delayed observation is persisted", Expected: "history", Component: "sensor/journal"},
	{ID: "late-frame-08", Trigger: "new sensor epoch starts", Expected: "new generation", Component: "sensor/incident"},
	{ID: "late-frame-09", Trigger: "old epoch is repeated", Expected: "archive", Component: "sensor/detector"},
	{ID: "late-frame-10", Trigger: "late image arrives after notice", Expected: "no duplicate notice", Component: "detector/dispatch"},
	{ID: "perimeter-01", Trigger: "wind bearing changes", Expected: "new revision", Component: "perimeter/dispatch"},
	{ID: "perimeter-02", Trigger: "new no-fly corridor is published", Expected: "route rejects zone", Component: "perimeter/aircraft"},
	{ID: "perimeter-03", Trigger: "old route remains active", Expected: "frozen old revision", Component: "aircraft/perimeter"},
	{ID: "perimeter-04", Trigger: "new flight is planned", Expected: "current revision", Component: "dispatch/aircraft"},
	{ID: "perimeter-05", Trigger: "route is frozen", Expected: "revision retained", Component: "aircraft/journal"},
	{ID: "perimeter-06", Trigger: "boundary expands east", Expected: "waypoint updates", Component: "perimeter/aircraft"},
	{ID: "perimeter-07", Trigger: "boundary update races planning", Expected: "one current input", Component: "perimeter/dispatch"},
	{ID: "perimeter-08", Trigger: "old revision is queried", Expected: "historical result", Component: "perimeter/api"},
	{ID: "perimeter-09", Trigger: "wind returns to prior bearing", Expected: "new revision id", Component: "perimeter/journal"},
	{ID: "perimeter-10", Trigger: "flight crosses a restricted zone", Expected: "planning error", Component: "aircraft/api"},
	{ID: "merge-01", Trigger: "two active fires become one", Expected: "primary incident", Component: "incident/dispatch"},
	{ID: "merge-02", Trigger: "child mission is migrated", Expected: "primary owner", Component: "incident/dispatch"},
	{ID: "merge-03", Trigger: "old radio acknowledgement arrives", Expected: "primary thread", Component: "incident/radio"},
	{ID: "merge-04", Trigger: "backup query sees an ack", Expected: "no duplicate crew", Component: "radio/dispatch"},
	{ID: "merge-05", Trigger: "child incident is queried", Expected: "historical alias", Component: "incident/api"},
	{ID: "merge-06", Trigger: "primary has two missions", Expected: "both retained", Component: "incident/dispatch"},
	{ID: "merge-07", Trigger: "child has no missions", Expected: "alias only", Component: "incident/journal"},
	{ID: "merge-08", Trigger: "merge is repeated", Expected: "stable result", Component: "incident/dispatch"},
	{ID: "merge-09", Trigger: "unrelated incidents merge", Expected: "reject", Component: "incident/sector"},
	{ID: "merge-10", Trigger: "merge is recovered", Expected: "one owner", Component: "journal/dispatch"},
	{ID: "cancel-01", Trigger: "reserved drop mission is cancelled", Expected: "release lease", Component: "dispatch/resource"},
	{ID: "cancel-02", Trigger: "cancel is repeated", Expected: "idempotent", Component: "dispatch/resource"},
	{ID: "cancel-03", Trigger: "release fails", Expected: "compensating", Component: "dispatch/resource"},
	{ID: "cancel-04", Trigger: "different mission cancels", Expected: "other lease intact", Component: "dispatch/resource"},
	{ID: "cancel-05", Trigger: "air route is cancelled", Expected: "route removed", Component: "dispatch/aircraft"},
	{ID: "cancel-06", Trigger: "water corridor is reused", Expected: "new lease", Component: "resource/dispatch"},
	{ID: "cancel-07", Trigger: "released lease is inspected", Expected: "release time", Component: "resource/api"},
	{ID: "cancel-08", Trigger: "stale token releases", Expected: "owner mismatch", Component: "resource/dispatch"},
	{ID: "cancel-09", Trigger: "cancel follows retry", Expected: "one mission", Component: "dispatch/radio"},
	{ID: "cancel-10", Trigger: "cancel is recovered", Expected: "consistent state", Component: "journal/resource"},
	{ID: "proof-01", Trigger: "field image writes successfully", Expected: "contain", Component: "crew/incident"},
	{ID: "proof-02", Trigger: "field image write fails", Expected: "remain attacking", Component: "crew/journal"},
	{ID: "proof-03", Trigger: "report is retried", Expected: "same report", Component: "crew/journal"},
	{ID: "proof-04", Trigger: "alert withdrawal follows proof", Expected: "withdrawn", Component: "incident/alert"},
	{ID: "proof-05", Trigger: "service restarts after proof", Expected: "evidence present", Component: "journal/incident"},
	{ID: "proof-06", Trigger: "empty report is submitted", Expected: "reject", Component: "crew/api"},
	{ID: "proof-07", Trigger: "missing image is submitted", Expected: "reject", Component: "crew/journal"},
	{ID: "proof-08", Trigger: "report metadata is durable", Expected: "index exists", Component: "journal/crew"},
	{ID: "proof-09", Trigger: "alert is still active", Expected: "public warning", Component: "alert/incident"},
	{ID: "proof-10", Trigger: "retry succeeds", Expected: "contained", Component: "incident/alert"},
	{ID: "retry-01", Trigger: "radio publish succeeds", Expected: "one mission", Component: "dispatch/radio"},
	{ID: "retry-02", Trigger: "result write fails", Expected: "recover operation", Component: "dispatch/journal"},
	{ID: "retry-03", Trigger: "same HTTP operation repeats", Expected: "same mission", Component: "api/dispatch"},
	{ID: "retry-04", Trigger: "different operation repeats", Expected: "new mission", Component: "api/dispatch"},
	{ID: "retry-05", Trigger: "radio broker returns timeout", Expected: "visible failure", Component: "radio/journal"},
	{ID: "retry-06", Trigger: "operation is recovered", Expected: "recorded result", Component: "dispatch/journal"},
	{ID: "retry-07", Trigger: "operation is failed", Expected: "error retained", Component: "journal/api"},
	{ID: "retry-08", Trigger: "retry budget expires", Expected: "operator action", Component: "dispatch/api"},
	{ID: "retry-09", Trigger: "duplicate message is inspected", Expected: "one identity", Component: "radio/dispatch"},
	{ID: "retry-10", Trigger: "queue drains", Expected: "send order", Component: "radio/queue"},
	{ID: "mode-01", Trigger: "visible calibration is active", Expected: "frame accepted", Component: "sensor/detector"},
	{ID: "mode-02", Trigger: "combined mode is requested", Expected: "wait calibration", Component: "sensor/detector"},
	{ID: "mode-03", Trigger: "combined calibration is published", Expected: "atomic profile", Component: "sensor/profile"},
	{ID: "mode-04", Trigger: "first combined frame arrives", Expected: "no panic", Component: "sensor/detector"},
	{ID: "mode-05", Trigger: "mode request has no snapshot", Expected: "explicit error", Component: "sensor/profile"},
	{ID: "mode-06", Trigger: "sensor restarts", Expected: "same revision", Component: "sensor/journal"},
	{ID: "mode-07", Trigger: "old mode frame arrives", Expected: "old calibration", Component: "sensor/detector"},
	{ID: "mode-08", Trigger: "calibration history is queried", Expected: "revisions", Component: "sensor/api"},
	{ID: "mode-09", Trigger: "profile revision differs", Expected: "not compatible", Component: "sensor/detector"},
	{ID: "mode-10", Trigger: "profile is ready", Expected: "accept input", Component: "sensor/stream"},
	{ID: "race-01", Trigger: "two corridor requests start together", Expected: "one owner", Component: "api/resource"},
	{ID: "race-02", Trigger: "first request commits", Expected: "second rejects", Component: "dispatch/resource"},
	{ID: "race-03", Trigger: "two different corridors", Expected: "both succeed", Component: "dispatch/resource"},
	{ID: "race-04", Trigger: "same mission retries", Expected: "same lease", Component: "dispatch/resource"},
	{ID: "race-05", Trigger: "release overlaps acquire", Expected: "ordered token", Component: "resource/dispatch"},
	{ID: "race-06", Trigger: "owner list is inspected", Expected: "one owner", Component: "resource/api"},
	{ID: "race-07", Trigger: "race detector runs", Expected: "no data race", Component: "resource/dispatch"},
	{ID: "race-08", Trigger: "request is cancelled", Expected: "lease released", Component: "dispatch/resource"},
	{ID: "race-09", Trigger: "request times out", Expected: "no orphan", Component: "api/resource"},
	{ID: "race-10", Trigger: "registry restarts", Expected: "active lease restored", Component: "journal/resource"},
	{ID: "alert-01", Trigger: "evacuation is published", Expected: "active alert", Component: "alert/api"},
	{ID: "alert-02", Trigger: "area is reduced", Expected: "updated message", Component: "alert/incident"},
	{ID: "alert-03", Trigger: "withdrawal succeeds", Expected: "inactive alert", Component: "alert/incident"},
	{ID: "alert-04", Trigger: "withdrawal broker fails", Expected: "pending alert", Component: "alert/incident"},
	{ID: "alert-05", Trigger: "broker recovers", Expected: "retry withdrawal", Component: "alert/retry"},
	{ID: "alert-06", Trigger: "contained state is queried", Expected: "alert visible", Component: "incident/api"},
	{ID: "alert-07", Trigger: "two alerts share area", Expected: "independent ids", Component: "alert/api"},
	{ID: "alert-08", Trigger: "alert is replayed", Expected: "same activity", Component: "journal/alert"},
	{ID: "alert-09", Trigger: "area has no alert", Expected: "not found", Component: "alert/api"},
	{ID: "alert-10", Trigger: "alert list is sorted", Expected: "update order", Component: "alert/api"},
	{ID: "recover-01", Trigger: "alias snapshot loads", Expected: "map first", Component: "journal/incident"},
	{ID: "recover-02", Trigger: "mission snapshot loads", Expected: "primary owner", Component: "journal/dispatch"},
	{ID: "recover-03", Trigger: "child snapshot loads", Expected: "closed child", Component: "journal/incident"},
	{ID: "recover-04", Trigger: "unmerged snapshot loads", Expected: "original owner", Component: "journal/dispatch"},
	{ID: "recover-05", Trigger: "recovery repeats", Expected: "stable indexes", Component: "journal/dispatch"},
	{ID: "recover-06", Trigger: "snapshot is incomplete", Expected: "error visible", Component: "journal/api"},
	{ID: "recover-07", Trigger: "event replay starts at cursor", Expected: "skip prior", Component: "journal/replay"},
	{ID: "recover-08", Trigger: "unknown event is strict", Expected: "replay error", Component: "journal/replay"},
	{ID: "recover-09", Trigger: "checkpoint is verified", Expected: "digest match", Component: "journal/checkpoint"},
	{ID: "recover-10", Trigger: "event retention runs", Expected: "recent events", Component: "journal/store"},
}

func ScenarioCount() int { return len(Scenarios) }
